/*
Airbyte Configuration API

Airbyte Configuration API [https://airbyte.io](https://airbyte.io).  This API is a collection of HTTP RPC-style methods. While it is not a REST API, those familiar with REST should find the conventions of this API recognizable.  Here are some conventions that this API follows: * All endpoints are http POST methods. * All endpoints accept data via `application/json` request bodies. The API does not accept any data via query params. * The naming convention for endpoints is: localhost:8000/{VERSION}/{METHOD_FAMILY}/{METHOD_NAME} e.g. `localhost:8000/v1/connections/create`. * For all `update` methods, the whole object must be passed in, even the fields that did not change.  Change Management: * The major version of the API endpoint can be determined / specified in the URL `localhost:8080/v1/connections/create` * Minor version bumps will be invisible to the end user. The user cannot specify minor versions in requests. * All backwards incompatible changes will happen in major version bumps. We will not make backwards incompatible changes in minor version bumps. Examples of non-breaking changes (includes but not limited to...):   * Adding fields to request or response bodies.   * Adding new HTTP endpoints.

API version: 1.0.0
Contact: contact@airbyte.io
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package airbyte_sdk

import (
	"encoding/json"
)

// HealthCheckRead struct for HealthCheckRead
type HealthCheckRead struct {
	Db bool `json:"db"`
}

// NewHealthCheckRead instantiates a new HealthCheckRead object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewHealthCheckRead(db bool) *HealthCheckRead {
	this := HealthCheckRead{}
	this.Db = db
	return &this
}

// NewHealthCheckReadWithDefaults instantiates a new HealthCheckRead object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewHealthCheckReadWithDefaults() *HealthCheckRead {
	this := HealthCheckRead{}
	return &this
}

// GetDb returns the Db field value
func (o *HealthCheckRead) GetDb() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Db
}

// GetDbOk returns a tuple with the Db field value
// and a boolean to check if the value has been set.
func (o *HealthCheckRead) GetDbOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Db, true
}

// SetDb sets field value
func (o *HealthCheckRead) SetDb(v bool) {
	o.Db = v
}

func (o HealthCheckRead) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["db"] = o.Db
	}
	return json.Marshal(toSerialize)
}

type NullableHealthCheckRead struct {
	value *HealthCheckRead
	isSet bool
}

func (v NullableHealthCheckRead) Get() *HealthCheckRead {
	return v.value
}

func (v *NullableHealthCheckRead) Set(val *HealthCheckRead) {
	v.value = val
	v.isSet = true
}

func (v NullableHealthCheckRead) IsSet() bool {
	return v.isSet
}

func (v *NullableHealthCheckRead) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableHealthCheckRead(val *HealthCheckRead) *NullableHealthCheckRead {
	return &NullableHealthCheckRead{value: val, isSet: true}
}

func (v NullableHealthCheckRead) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableHealthCheckRead) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
